Repository wecode-bootcamp-korea/30-2nd-AirFlyer-frontend, pull requests merged in 2022-03, with the labels that each got.

#4 [30기 김혜진/Common] 공통 폰트, GlobalStyle, theme 수정 완료
  src/Router.js
  src/components/WrapperLayout/WrapperLayout.js
  src/hooks/hooks.js
  src/pages/Login/Login.js
  src/styles/GlobalStyle.js
  src/styles/fonts/NanumGothic-Bold.ttf
  src/styles/fonts/NanumGothic-ExtraBold.ttf
  src/styles/fonts/NanumGothic-Regular.ttf
  src/styles/fonts/NotoSansKR-Black.woff
  src/styles/fonts/NotoSansKR-Bold.woff
  src/styles/fonts/NotoSansKR-Light.woff
  src/styles/fonts/NotoSansKR-Medium.woff
  src/styles/fonts/NotoSansKR-Regular.woff
  src/styles/fonts/NotoSansKR-Thin.woff
  src/styles/fonts/fonts.js
  src/styles/theme.js
Labels: Status: Accepted

#1 [30기 김혜진/Nav] 1차 리뷰 반영 완료 (IconButton 컴포넌트 재사용, NavLink 스타일링 완)
  public/images/alram.png
  public/images/cart.png
  public/images/logo.png
  public/images/search.png
  src/components/Nav/Nav.js
  src/components/Nav/navdata.js
  src/components/WrapperLayout/WrapperLayout.js
  src/styles/GlobalStyle.js
  src/styles/fonts/NanumGothic-Bold.ttf
  src/styles/fonts/NanumGothic-ExtraBold.ttf
  src/styles/fonts/NanumGothic-Regular.ttf
  src/styles/fonts/fonts.js
Labels: Status: Accepted

#7 [30기 김혜진/common] master에서 fonts 폴더 삭제되어 재푸쉬
  src/components/WrapperLayout/WrapperLayout.js
  src/styles/fonts/NanumGothic-Bold.ttf
  src/styles/fonts/NanumGothic-ExtraBold.ttf
  src/styles/fonts/NanumGothic-Regular.ttf
  src/styles/fonts/fonts.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#9 [30기 김혜진/Nav] IconButton 컴포넌트 재사용
  .gitignore
  public/images/mypage.png
  src/components/Icon/IconButton/IconButton.js
  src/components/Nav/Nav.js
  src/components/Nav/navdata.js
Labels: Status: 리뷰 요청

#12 [30기 김혜진/Common] 1차 리뷰 반영 완료
  src/components/Icon/IconButton/IconButton.js
  src/components/Modal/Modal.js
  src/components/Nav/Nav.js
  src/components/WrapperLayout/WrapperLayout.js
  src/index.js
  src/redux/counter.js
  src/redux/date.js
  src/redux/index.js
  src/redux/isModalOpen.js
  src/redux/location.js
  src/redux/modalInfo.js
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: Status: 리뷰 요청

#14 [30기 강성훈 footer] 레이아웃 최종수정
  public/images/logo_black.png
  src/components/Footer/Footer.js
Labels: Status: Rebase 요청

#3 [30기 김혜진/Main] 2차 리뷰 반영 완료
  package-lock.json
  package.json
  public/data/planetList.json
  public/images/calendar.png
  public/images/change.png
  public/images/change_active.png
  public/images/mainBanner.jpg
  public/images/mainBannerLogo.jpeg
  public/images/mainBannerLogov2.jpg
  public/images/pin.png
  public/images/rocket.png
  public/images/user.png
  src/Router.js
  src/components/Modal/Modal.js
  src/hooks/hooks.js
  src/hooks/useLockBodyScroll.js
  src/pages/Main/Calendar/Calendar.js
  src/pages/Main/LocationPicker/LocationList.js
  src/pages/Main/LocationPicker/LocationPicker.js
  src/pages/Main/LocationPicker/categoryData.js
  src/pages/Main/Main.js
  src/pages/Main/PassengerPicker/PassengerPicker.js
  src/pages/Main/PassengerPicker/passengerTypeData.js
  src/pages/Main/SearchBar/SearchBar.js
  src/pages/Main/bookingTypeData.js
  src/redux/counter.js
  src/redux/modalInfo.js
Labels: Status: 리뷰 요청

#5 [30기 안광민/Login] 로그인 레이아웃 및 소셜로그인 토큰 백엔드 통신 완료
  public/images/kakao_login_large_narrow.png
  public/images/kakao_login_large_wide.png
  public/images/kakao_login_medium_narrow.png
  public/images/kakao_login_medium_wide.png
  public/index.html
  src/pages/Login/Login.js
Labels: Status: Accepted

#11 [30기 김혜진/MyPage] 1차 리뷰 반영 완료
  package-lock.json
  package.json
  public/data/ticketListData.json
  public/images/blank.png
  public/pdf/ticket_sample.pdf
  src/hooks/hooks.js
  src/pages/Main/Calendar/Calendar.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/PdfModal.js
  src/redux/modalInfo.js
  src/utils/storage.js
Labels: Status: 리뷰 요청

#6 [30기 안광민/Traverlerinfo] 양식작성 페이지
  public/data/mockData.json
  public/images/down_arrow.png
  public/images/down_arrow_white.png
  src/Router.js
  src/pages/TravelerInfo/PriceAside/PriceAside.js
  src/pages/TravelerInfo/ReservationInfo/Caution/Caution.js
  src/pages/TravelerInfo/ReservationInfo/PassengerInfo/PassengerInfo.js
  src/pages/TravelerInfo/ReservationInfo/ReservationInfo.js
  src/pages/TravelerInfo/ReservationInfo/TicketInfo/TicketInfo.js
  src/pages/TravelerInfo/TravelerInfo.js
Labels: Status: 리뷰 요청

#13 [30기 강성훈/ Flightslist page] 레이아웃 완료, 기능 구현완료 ver 0
  package-lock.json
  package.json
  public/data/mockData.json
  public/images/saturn.png
  src/Router.js
  src/components/Footer/Footer.js
  src/pages/FlightsList/FlgithCard/FlightCard.js
  src/pages/FlightsList/FlightWidgetFix/FlightWidgetFix.js
  src/pages/FlightsList/FlightsList.js
  src/pages/FlightsList/TotalPriceBar/TotalPriceBar.js
  src/pages/FlightsList/flightsListData.js
  src/redux/index.js
  src/redux/location.js
  src/redux/ticketInfo.js
  src/redux/totalFare.js
Labels: Status: 리뷰 요청
